Website/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
]

Website/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.static import static 
from django.contrib import admin
from django.conf import settings

app_name = "photo_gallery"

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls')),
    url(r'^photo_gallery/', include('photo_gallery.urls', namespace='photo_gallery')),
    url(r'^resume/', include('resume.urls', namespace='resume'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/photo_gallery/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = "photo_gallery"

urlpatterns = [
    url(r'^$', views.flickr_photos, name='photo_list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website/resume/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "resume"

urlpatterns = [
    url(r'^$', views.resume, name='resume')
]

Website/blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=None)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

Website/photo_gallery/models.py
from __future__ import unicode_literals
# from cloudinary.models import CloudinaryField
from django.db import models


# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=200)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    image = models.ImageField(null=False, blank=False, width_field="width", height_field="height") 
    timestamp =  models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp"]

Website/resume/models.py
from django.db import models

# Create your models here.

Website/blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class NameForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

Website/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm, NameForm


# Create your views here.


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_index.html', {'posts': posts})


def post_detail(request, pk):
    posts = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': posts})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        form2 = NameForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
        form2 = NameForm()
    return render(request, 'blog/post_edit.html', {'form': form, 'form2': form2})

Website/photo_gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Photo 
from django.conf import settings
from django.views.decorators.cache import cache_page
from flickr_pony.storage import FlickrStorage
from el_pagination.decorators import page_template
from el_pagination.views import AjaxListView
import photo_gallery.PhotoGalleryCustomClasses.flickr_api as FlickApi


@cache_page(60*30)
def flickr_photos(request, template='base.html', page_template='photo.html'):
    flickr = FlickApi.FlickrAPI(request)
    flickr_photos = flickr.get_pictures_as_list('L', False)

    context = {
        'entry_list': flickr_photos,
        'page_template': page_template,
    }

    if request.is_ajax():
        template = page_template

    return render(request, template, context)

Website/resume/views.py
from django.shortcuts import render
from django.http import HttpResponse

def resume(request):
    return render(request, 'resume/resume.html')

Website/blog/templates/blog/base.html
{% extends "global/navbar.html" %}

{% block base_content%}
 <div class="content container">
            {% block content %}
            {% endblock %}
</div>  
{% endblock %}


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

Website/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content%}

<main role="main">
    <div class="jumbotron">
        <div class="container">
            <div class="col-lg-10 mx-auto">
                <h1>{{ post.title }}</h1>
                <p>{{ post.text|linebreaksbr }}</p>
            </div>
        </div>
    </div>
</main>
    <!-- /.container -->

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="post">
        </div>
    </div>
{% endblock %}

Website/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block post %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

Website/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
<main role="main">
    <div class="jumbotron">
        <div class="container">
            <div class="col-lg-10 mx-auto">
                <h1 class="display-3">Your Average Human</h1>
                <p>
                    This is my on going web programming project as well as my personal blog and photo. Please bare with me as a lot of things will look out of place
                as I progress my knowledge with web technologies and my understanding on how to implement them in a way that I find useful and aesthetically pleasing.
                Thanks for stopping by and if you have any suggestions don't hesitate to contact me.
                </p>
            </div>
        </div>
    </div>
    <!-- /.container -->



    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            {% for post in posts %}
            <div class="col-lg-8 col-md-10 mx-auto">
                <h3><a href="{% url 'post_detail' pk=post.pk %}">{{post.title}}</a> </h3>
                <p>{{ post.text }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
        <hr>
</main>

{% endblock %}

Website/photo_gallery/templates/base.html
{% extends "global/navbar.html" %}

{% block base_content %}
  <main role="main">
      <div class="jumbotron">
          <div class="container">
              <h1 class="display-3">Photo Gallery</h1>
              <p>I recently took an interest in photography so this gallery is to share some
              of my favorite pictures that I have taken. If you like them and want to use any
                just contact me and we will work something out.</p>
          </div>
      </div>

  </main>

  <div class="content container">
          <div>
              {% block photo%}
                {% include page_template %}
              {% endblock %}
          </div>
  </div>

  <script>
      window.onload = function() {
          if (window.jQuery) {  
              // jQuery is loaded  
              alert("Yeah!");
          } else {
              // jQuery is not loaded
              alert("Doesn't Work");
          }
      }
  </script>
{% endblock %}

Website/photo_gallery/templates/photo.html
{% load el_pagination_tags %}
{% block photo %}


    <div class="row">
    {% lazy_paginate entry_list %}
    {% for entry in entry_list%}
            <div class="col-md-2 ">
                <img class="img-fluid mx-auto d-block img-thumbnail" src="{{ entry }}" />
            </div>
    {% endfor %}
    </div>
    {% show_more '<button type="button" class="btn">Loading ...</button>' %}

{% endblock %}

Website/resume/templates/resume/base.html
{% extends "global/navbar.html" %}
{% block base_content%}
    {% comment %} <div class="content container"> {% endcomment %}
        {% block content %}
        
        {% endblock %}
    {% comment %} </div> {% endcomment %}
{% endblock %}

Website/resume/templates/resume/resume.html
{% extends "resume/base.html" %}
{% block content%}
<main role="main">
    <div class="jumbotron">
        <div class="container">
            <div class="col-lg-10 mx-auto">
                <h1 class="display-3">Resume</h1>
                <p>
                    (PLACE HOLDER)... This will by where I put my resume
                </p>
            </div>
        </div>
    </div>
</main>

{% endblock %}

Website/templates/global/navbar.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>YourAverageHuman</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"/>
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous">
    </script>
</head>
<body>

    <!-- Global top nav bar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="#">YAH</a>
            </div>
            
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav text-nowrap flex-row mx-md-auto order-1 order-md-2">
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/">Blog</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link"href="{% url 'photo_gallery:photo_list' %}">Photos</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link"href="{% url 'resume:resume' %}">Resume</a>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <!-- End of Nav Bar-->
    {% block base_content %}
    {% endblock %}
</body>